### ISSUE TITLE
Sophus ensure failed in function

### ISSUE THREAD

**Issue by yangcc0503** [PRBonn/MapClosures#79]
I tried to run this on the KITTI odometry dataset (velodyne laser data + calibration + gt), but it didn't work properly. I use WSL2 with Ubuntu22.04.

**Sophus ensure failed in function 'static Sophus::SO3<Scalar_> Sophus::SO3<Scalar_, Options>::expAndTheta(const Tangent&, Sophus::SO3<Scalar_, Options>::Scalar*) [with Scalar_ = double; int Options = 0; Sophus::SO3<Scalar_, Options>::Tangent = Eigen::Matrix<double, 3, 1>; Sophus::SO3<Scalar_, Options>::Scalar = double]', file '/project/python/build/cp310-cp310-linux_x86_64/_deps/sophus-src/sophus/so3.hpp', line 725.
SO3::exp failed! omega: {}, real: {}, img: {}**

**Comment by saurabh1002** [comment]
What is the version of kiss-icp and map-closures installed on your machine?

**Comment by saurabh1002** [comment]
If you install map-closure, kiss-icp is automatically installed if not already installed by you. So I don't think that is the problem.
The above issue occurs mainly due to the timestamp API change in KISS-ICP. We have updated the dataloaders in #76 to match the requirements for KISS-ICP >=1.2.3 version.

If you install map-closures from the main branch on this repo, the above issue should be resolved.

**Comment by yangcc0503** [comment]
Apologies for the repeated trouble. It still doesn't work, and I've already cloned the latest version from the main branch. Could I have overlook something?

![Image](https://github.com/user-attachments/assets/281422bc-0c6b-434c-82e4-f3c49ed63b4c)

**Comment by saurabh1002** [comment]
I noticed a bug with the KITTI dataloader related to the `sequence` parsing, which I fix in a new PR which I will merge soon to main.
However, that had nothing to do with the error you get with Sophus. I get the following results:

<img width="2026" height="1347" alt="Image" src="https://github.com/user-attachments/assets/fffa5edc-40ea-498a-80c4-756097f4ac81" />

<img width="2549" height="904" alt="Image" src="https://github.com/user-attachments/assets/924d59af-5709-4945-8b25-97c455e07176" />

Could you provide the output for 'kiss_icp_pipeline --version`?

**Comment by saurabh1002** [comment]
This looks right. Can you try again using the `fix_kitti_dataloader` branch from this repo?

**Comment by yangcc0503** [comment]
It's still not working, but the number of errors has decreased.

![Image](https://github.com/user-attachments/assets/7310e03d-ab43-4c49-945a-0db73ba37e80)

**Comment by saurabh1002** [comment]
I am not sure what the error is in this case. Can you double check if you are using the raw data and it is not modified by any chance? Could you try using our [lidar visualizer](https://github.com/PRBonn/lidar-visualizer) tool to just visualize the raw scans and see if that works? You need to just pass it the Velodyne scans directory directly.

The WSL system could also be a potential issue. Could you try on a Linux machine to see if the error persists?

**Comment by yangcc0503** [comment]
Lidar visualizer works. Afterwards, I deleted the entire dataset and re-extracted it, but is still fails to run. As for the Linux machine, it will take some time to set up, so I will first try running it on another dataset. Thanks for your help.

![Image](https://github.com/user-attachments/assets/e1413a00-5a3f-4df1-884a-5624e689569d)
